package write;

public class mxg {
	static final String[] mxg = {
			//female
			"Mary", "Patricia", "Linda", "Barbara", "Elizabeth", "Jennifer", "Maria", "Susan",
			"Margaret", "Dorothy", "Lisa", "Nancy", "Karen", "Betty", "Helen", "Sandra", "Donna",
			"Carol", "Ruth", "Sharon", "Michelle", "Laura", "Sarah", "Kimberly", "Deborah", "Jessica",
			"Shirley", "Cynthia", "Angela", "Melissa", "Brenda", "Amy", "Anna", "Rebecca", "Virginia",
			"Kathleen", "Pamela", "Martha", "Debra", "Amanda", "Stephanie", "Carolyn", "Christine",
			"Marie", "Janet", "Catherine", "Frances", "Ann", "Joyce", "Diane", "Alice", "Julie",
			"Heather", "Teresa", "Doris", "Gloria", "Evelyn", "Jean", "Cheryl", "Mildred", "Katherine",
			"Joan", "Ashley", "Judith", "Rose", "Janice", "Kelly", "Nicole", "Judy", "Christina",
			"Kathy", "Theresa", "Beverly", "Denise", "Tammy", "Irene", "Jane", "Lori", "Rachel",
			"Marilyn", "Andrea", "Kathryn", "Louise", "Sara", "Anne", "Jacqueline", "Wanda", "Bonnie",
			"Julia", "Ruby", "Lois", "Tina", "Phyllis", "Norma", "Paula", "Diana", "Annie", "Lillian",
			"Emily", "Robin", "Peggy", "Crystal", "Gladys", "Rita", "Dawn", "Connie", "Florence",
			"Tracy", "Edna", "Tiffany", "Carmen", "Rosa", "Cindy", "Grace", "Wendy", "Victoria", "Edith",
			"Kim", "Sherry", "Sylvia", "Josephine", "Thelma", "Shannon", "Sheila", "Ethel", "Ellen",
			"Elaine", "Marjorie", "Carrie", "Charlotte", "Monica", "Esther", "Pauline", "Emma",
			"Juanita", "Anita", "Rhonda", "Hazel", "Amber", "Eva", "Debbie", "April", "Leslie", "Clara",
			"Lucille", "Jamie", "Joanne", "Eleanor", "Valerie", "Danielle", "Megan", "Alicia", "Suzanne",
			"Michele", "Gail", "Bertha", "Darlene", "Veronica", "Jill", "Erin", "Geraldine", "Lauren",
			"Cathy", "Joann", "Lorraine", "Lynn", "Sally", "Regina", "Erica", "Beatrice", "Dolores",
			"Bernice", "Audrey", "Yvonne", "Annette", "June", "Samantha", "Marion", "Dana", "Stacy",
			"Ana", "Renee", "Ida", "Vivian", "Roberta", "Holly", "Brittany", "Melanie", "Loretta",
			"Yolanda", "Jeanette", "Laurie", "Katie", "Kristen", "Vanessa", "Alma", "Sue", "Elsie",
			"Beth", "Jeanne",
			
			//male
			"James", "John", "Robert", "Michael", "William", "David", "Richard", "Charles", "Joseph",
			"Thomas", "Christopher", "Daniel", "Paul", "Mark", "Donald", "George", "Kenneth", "Steven",
			"Edward", "Brian", "Ronald", "Anthony", "Kevin", "Jason", "Matthew", "Gary", "Timothy",
			"Jose", "Larry", "Jeffrey", "Frank", "Scott", "Eric", "Stephen", "Andrew", "Raymond",
			"Gregory", "Joshua", "Jerry", "Dennis", "Walter", "Patrick", "Peter", "Harold", "Douglas",
			"Henry", "Carl", "Arthur", "Ryan", "Roger", "Joe", "Juan", "Jack", "Albert", "Jonathan",
			"Justin", "Terry", "Gerald", "Keith", "Samuel", "Willie", "Ralph", "Lawrence", "Nicholas",
			"Roy", "Benjamin", "Bruce", "Brandon", "Adam", "Harry", "Fred", "Wayne", "Billy", "Steve",
			"Louis", "Jeremy", "Aaron", "Randy", "Howard", "Eugene", "Carlos", "Russell", "Bobby",
			"Victor", "Martin", "Ernest", "Phillip", "Todd", "Jesse", "Craig", "Alan", "Shawn",
			"Clarence", "Sean", "Philip", "Chris", "Johnny", "Earl", "Jimmy", "Antonio", "Danny",
			"Bryan", "Tony", "Luis", "Mike", "Stanley", "Leonard", "Nathan", "Dale", "Manuel", "Rodney",
			"Curtis", "Norman", "Allen", "Marvin", "Vincent", "Glenn", "Jeffery", "Travis", "Jeff",
			"Chad", "Jacob", "Lee", "Melvin", "Alfred", "Kyle", "Francis", "Bradley", "Jesus", "Herbert",
			"Frederick", "Ray", "Joel", "Edwin", "Don", "Eddie", "Ricky", "Troy", "Randall", "Barry",
			"Alexander", "Bernard", "Mario", "Leroy", "Francisco", "Marcus", "Micheal", "Theodore",
			"Clifford", "Miguel", "Oscar", "Jay", "Jim", "Tom", "Calvin", "Alex", "Jon", "Ronnie",
			"Bill", "Lloyd", "Tommy", "Leon", "Derek", "Warren", "Darrell", "Jerome", "Floyd", "Leo",
			"Alvin", "Tim", "Wesley", "Gordon", "Dean", "Greg", "Jorge", "Dustin", "Pedro", "Derrick",
			"Dan", "Lewis", "Zachary", "Corey", "Herman", "Maurice", "Vernon", "Roberto", "Clyde",
			"Glen", "Hector", "Shane", "Ricardo", "Sam", "Rick", "Lester", "Brent", "Ramon", "Charlie",
			"Tyler", "Gilbert", "Gene"};
			
	static final String[] mxgc = {
			
	//女性
	"玛丽","帕特丽夏","琳达","芭芭拉","伊丽莎白","詹妮弗","玛丽亚","苏珊",
	"玛格丽特","多萝西","丽莎","南希","凯伦","贝蒂","海伦","桑德拉","唐娜",
	"卡罗尔","露丝","莎伦","米歇尔","劳拉","莎拉","金伯利","黛博拉","杰西卡",
	"雪莉","辛西娅","安吉拉","梅丽莎","布伦达","艾米","安娜","丽贝卡","弗吉尼亚",
	"凯瑟琳","帕梅拉","玛莎","黛布拉","阿曼达","斯蒂芬妮","卡罗琳","克里斯蒂娜",
	"玛丽","珍妮特","凯瑟琳","弗朗西斯","安","乔伊斯","黛安娜","爱丽丝","朱莉",
	"希瑟","特蕾莎","多丽丝","格洛丽亚","伊芙琳","琼","谢丽尔","米尔德里德","凯瑟琳",
	"琼","艾希礼","朱迪丝","罗斯","珍妮丝","凯莉","妮可","朱迪","克里斯蒂娜",
	"凯西","特里萨","贝弗利","丹尼斯","塔米","艾琳","简","洛莉","瑞秋",
	"玛丽莲","安德烈","凯瑟琳","路易丝","萨拉","安妮","杰奎琳","旺达","邦妮",
	"朱莉娅","鲁比","露易丝","蒂娜","菲利斯","诺玛","宝拉","黛安娜","安妮","莉莲",
	"艾米丽","罗宾","佩吉","克里斯托","格拉迪斯","丽塔","黎明","康妮","佛罗伦萨",
	"特蕾西","埃德娜","蒂芙尼","卡门","罗莎","辛迪","格瑞丝","温迪","维克多利亚","伊迪丝",
	"金","雪莉","西尔维亚","约瑟芬","塞尔玛","香农","希拉","埃塞尔","艾伦",
	"伊莲","马乔莉","嘉莉","夏洛特","莫妮卡","埃丝特","波琳","爱玛",
	"胡安妮塔","安妮塔","朗达","榛子","琥珀","伊娃","黛比","艾普罗","莱斯利","克拉拉",
	"露西尔","杰米","乔安妮","埃莉诺","瓦莱丽","丹妮尔","梅根","艾丽西亚","苏珊娜",
	"米歇尔","盖尔","贝莎","达莲娜","维罗妮卡","吉尔","叶林","杰拉尔丁","劳伦",
	"凯西","乔安","洛林","林恩","莎莉","瑞吉娜","艾丽卡","比阿特丽斯","多洛丽丝",
	"伯妮丝","奥黛丽","伊冯","安妮特","琼","萨曼莎","玛丽安","达娜","斯泰西",
	"安娜","蕾妮","艾达","薇薇安","罗伯塔","霍莉","布列塔尼","梅勒妮","洛蕾塔",
	"尤兰达","珍妮特","劳丽","凯蒂","克里斯汀","凡妮莎","阿尔玛","苏","埃尔西",
	"贝丝","珍妮",
	//男性
	"詹姆斯","约翰","罗伯特","迈克尔","威廉","大卫","理查德","查尔斯","约瑟夫",
	"托马斯","克里斯托弗","丹尼尔","保罗","马克","唐纳德","乔治","肯尼斯","史蒂文",
	"爱德华","布莱恩","罗纳德","安东尼","凯文","杰森","马修","加里","蒂莫西",
	"何塞","拉里","杰弗里","弗兰克","斯科特","埃里克","斯蒂芬","安德鲁","雷蒙德",
	"格雷戈里","约书亚","杰瑞","丹尼斯","沃尔特","帕特里克","彼得","哈罗德","道格拉斯",
	"亨利","卡尔","亚瑟","瑞安","罗杰","乔","胡安","杰克","艾伯特","乔纳森",
	"贾斯汀","特里","杰拉尔德","基思","塞缪尔","威利","拉尔夫","劳伦斯","尼古拉斯",
	"罗伊","本杰明","布鲁斯","布兰登","亚当","哈利","弗雷德","韦恩","比利","史蒂夫",
	"路易斯","杰里米","艾伦","兰迪","霍华德","尤金","卡洛斯","拉塞尔","鲍比",
	"维克多","马丁","欧内斯特","菲利普","托德","杰西","克雷格","艾伦","肖恩",
	"克拉伦斯","肖恩","菲利普","克里斯","约翰尼","厄尔","吉米","安东尼奥","丹尼",
	"布莱恩","托尼","路易斯","迈克","斯坦利","伦纳德","内森","戴尔","曼纽尔","罗德尼",
	"柯蒂斯","诺曼","艾伦","马文","文森特","格伦","杰弗里","特拉维斯","杰夫",
	"查德","雅各布","李","梅尔文","阿尔弗雷德","凯尔","弗朗西斯","布拉德利","耶稣","赫伯特",
	"弗雷德里克","雷","乔尔","埃德温","唐","埃迪","瑞奇","特洛伊","兰德尔","巴里",
	"亚历山大","伯纳德","马里奥","勒罗伊","弗朗西斯科","马库斯","迈克尔","西奥多",
	"克利福德","米格尔","奥斯卡","杰","吉姆","汤姆","加尔文","艾利克斯","乔恩","罗尼",
	"比尔","劳埃德","汤米","利昂","德里克","沃伦","达雷尔","杰罗姆","弗洛伊德","利奥",
	"阿尔文","蒂姆","卫斯理","戈登","迪安","格雷格","豪尔赫","达斯汀","佩德罗","德里克",
	"丹","刘易斯","扎卡里","科里","赫尔曼","莫里斯","弗农","罗伯托","克莱德",
	"格伦","赫克托","肖恩","里卡多","萨姆","里克","莱斯特","布伦特","雷蒙","查理",
	"泰勒","吉尔伯特","吉恩"};
}
