package write;

public class xxg {
	static final String[] xxg = {
			"Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore",
			"Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia",
			"Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen",
			"Young", "Hernandez", "King", "Wright", "Lopez", "Hill", "Scott", "Green", "Adams", "Baker",
			"Gonzalez", "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips",
			"Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Sanchez", "Morris",
			"Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper",
			"Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James",
			"Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross",
			"Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes",
			"Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant", "Alexander",
			"Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford", "Hamilton", "Graham", "Sullivan",
			"Wallace", "Woods", "Cole", "West", "Jordan", "Owens", "Reynolds", "Fisher", "Ellis",
			"Harrison", "Gibson", "Mcdonald", "Cruz", "Marshall", "Ortiz", "Gomez", "Murray", "Freeman",
			"Wells", "Webb", "Simpson", "Stevens", "Tucker", "Porter", "Hunter", "Hicks", "Crawford",
			"Henry", "Boyd", "Mason", "Morales", "Kennedy", "Warren", "Dixon", "Ramos", "Reyes", "Burns",
			"Gordon", "Shaw", "Holmes", "Rice", "Robertson", "Hunt", "Black", "Daniels", "Palmer",
			"Mills", "Nichols", "Grant", "Knight", "Ferguson", "Rose", "Stone", "Hawkins", "Dunn",
			"Perkins", "Hudson", "Spencer", "Gardner", "Stephens", "Payne", "Pierce", "Berry",
			"Matthews", "Arnold", "Wagner", "Willis", "Ray", "Watkins", "Olson", "Carroll", "Duncan",
			"Snyder", "Hart", "Cunningham", "Bradley", "Lane", "Andrews", "Ruiz", "Harper", "Fox",
			"Riley", "Armstrong", "Carpenter", "Weaver", "Greene", "Lawrence", "Elliott", "Chavez",
			"Sims", "Austin", "Peters", "Kelley", "Franklin", "Lawson"};
	static final String[] xxgc = {
	"史密斯","约翰逊","威廉姆斯","琼斯","布朗","戴维斯","米勒","威尔逊","摩尔",
	"泰勒","安德森","托马斯","杰克逊","怀特","哈里斯","马丁","汤普森","加西亚",
	"马丁内斯","罗宾逊","克拉克","罗德里格斯","刘易斯","李","沃克","霍尔","艾伦",
	"杨","埃尔南德斯","金","莱特","洛佩兹","希尔","斯科特","格林","亚当斯","贝克",
	"冈萨雷斯","纳尔逊","卡特","米切尔","佩雷斯","罗伯茨","特纳","菲利普斯",
	"坎贝尔","帕克","埃文斯","爱德华兹","柯林斯","斯图尔特","桑切斯","莫里斯",
	"罗杰斯","里德","库克","摩根","贝尔","墨菲","贝利","里维拉","库珀",
	"理查森","考克斯","霍华德","沃德","托雷斯","彼得森","格雷","拉米雷斯","詹姆斯",
	"沃森","布鲁克斯","凯利","桑德斯","普莱斯","班纳特","伍德","巴恩斯","罗斯",
	"亨德森","科尔曼","詹金斯","佩里","鲍威尔","朗","帕特森","休斯",
	"弗洛雷斯","华盛顿","巴特勒","西蒙斯","福斯特","冈萨雷斯","布莱恩特","亚历山大",
	"拉塞尔","格里芬","迪亚兹","海斯","迈尔斯","福特","汉密尔顿","格雷厄姆","沙利文",
	"华莱士","伍兹","科尔","韦斯特","乔丹","欧文斯","雷诺兹","费舍尔","埃利斯",
	"哈里森","吉布森","麦当劳","克鲁兹","马歇尔","奥尔蒂斯","戈麦斯","默里","弗里曼",
	"威尔斯","韦伯","辛普森","史蒂文斯","塔克","波特","亨特","希克斯","克劳福德",
	"亨利","博伊德","梅森","莫拉莱斯","肯尼迪","沃伦","迪克森","拉莫斯","雷耶斯","伯恩斯",
	"戈登","肖","福尔摩斯","赖斯","罗伯逊","亨特","布莱克","丹尼尔斯","帕尔默",
	"米尔斯","尼科尔斯","格兰特","奈特","弗格森","罗斯","石头","霍金斯","邓恩",
	"珀金斯","哈德逊","斯宾塞","加德纳","斯蒂芬斯","佩恩","皮尔斯","贝瑞",
	"马修斯","阿诺德","瓦格纳","威利斯","雷","沃特金斯","奥尔森","卡罗尔","邓肯",
	"斯奈德","哈特","坎宁安","布拉德利","莱恩","安德鲁斯","鲁伊斯","哈珀","福克斯",
	"莱利","阿姆斯特朗","卡彭特","韦弗","格林","劳伦斯","艾略特","查韦斯",
	"西姆斯","奥斯汀","彼得斯","凯利","富兰克林","劳森"};
}
